language: node_js
node_js:
  - 7
  - 6
notifications:
  email: false
sudo: false
script:
  - npm run test
  - npm run build
after_success:
  - rm -fr ./dist
  - NODE_ENV=production npm run build
  - npm run cover